name: CD Dir1
on:
  push:
    paths:
      - 'dir1/*'
      - 'common/*'
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello dir1
    steps:
    - name: Get the output time
      run: echo "The time was dir1 ${{ steps.hello.outputs.time }}"
