name: CD Dir2
on:
  push:
    paths:
      - 'dir2/*'
      - 'common/*'
    branches:
      - master
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello dir2
    steps:
    - name: Get the output time
      run: echo "The time was dir2 ${{ steps.hello.outputs.time }}"
